const images = {
  photo1: require("./1.webp"),
  photo1hov: require("./1hov.webp"),
  photo2: require("./2.webp"),
  photo2hov: require("./2hov.webp"),
  photo3: require("./3.webp"),
  photo3hov: require("./3hov.webp"),
  photo4: require("./4.webp"),
  photo4hov: require("./4hov.webp"),
  photo5: require("./5.webp"),
  photo5hov: require("./5hov.webp"),
  photo6: require("./6.webp"),
  photo6hov: require("./6hov.webp"),
  photo7: require("./7.webp"),
  photo7hov: require("./7hov.webp"),
  photo8: require("./8.webp"),
  photo8hov: require("./8hov.webp"),
  photo9: require("./9.webp"),
  photo9hov: require("./9hov.webp"),
  photo10: require("./10.webp"),
  photo10hov: require("./10hov.webp"),
  photo11: require("./11.webp"),
  photo11hov: require("./11hov.webp"),
  photo12: require("./12.webp"),
  photo12hov: require("./12hov.webp"),
  photo13: require("./13.webp"),
  photo13hov: require("./13hov.webp"),
  photo14: require("./14.webp"),
  photo14hov: require("./14hov.webp"),
  photo15: require("./15.webp"),
  photo15hov: require("./15hov.webp"),
  photo16: require("./16.webp"),
  photo16hov: require("./16hov.webp"),
};

export default images;
